javascript-lesson3
blank-4/exercises-Chrisahn75 pull request #15
Opened 2018-11-27 16:36 UTC by Chrisahn75

2018-11-27 16:53 UTC, yohanngab reviewed
ok!

Essaye d'utiliser des noms de fonctions qui correspondent à leur action

2018-11-27 16:55 UTC, yohanngab commented on javascript/lesson3/exercise2/exercise/index.js
> +function commande (garniture ,pate) {
L'espace doit être après la virgule, pas avant.

2018-11-27 16:55 UTC, yohanngab commented on javascript/lesson3/exercise2/exercise/index.js
> +    console.log("commande:une pizza" + garniture + pate);
Il faut que tu utilises la concaténation entre une chaine de caractere et tes variable afin de rajouter des espaces : 
"commande:une pizza" + garniture+" "+pate

2018-11-27 16:55 UTC, yohanngab commented on javascript/lesson3/exercise2/exercise/index.js
> +commande ("barbecue","cheezycrust");
Espace pas utile entre le nom de ta fonction et la parenthèse

2018-11-29 09:49 UTC, Neilsafraoui requested changes
voir commentaires, il y a quelques changements à faire

2018-11-29 09:49 UTC, Neilsafraoui commented on javascript/lesson3/exercise3/exercise/index.js
> +var boiteauLettres
selon l'énoncé : "Dans cette fonction on va mettre une variable "boiteAuLettres" "
la variable boiteauLettres doit etre dans la fonction. / ! \ ne pas oublier le point virgule à la fin d'une déclaration de variable

2018-11-29 09:49 UTC, Neilsafraoui commented on javascript/lesson3/exercise3/exercise/index.js
> +var monAppartement = function anonymous(boiteauLettres) {
le mot clé "anonymous" est de trop, il n'y a pas besoin de l'écrire

2018-11-29 09:49 UTC, Neilsafraoui commented on javascript/lesson3/exercise3/exercise/index.js
> +    console.log("Etage : " + "" +etage + "" + "Porte : " + "" +porte + "" + "Boite aux Lettres : " + "" +boiteauLettres + "" );
tu as beaucoup de chaines de caractères vides "inutiles"
la concaténation plus simple serait : console.log("Etage : " + etage + " Porte : " + porte + " boite aux lettres : " + boiteauLettres);

2018-11-29 09:57 UTC, FaXaq commented on javascript/lesson3/exercise3/exercise/index.js
> +    console.log("Etage : " + etage + " Porte : " + porte + " boite aux lettres : " + boiteauLettres );
top mais pas d'espaces avant une parenthèse

2018-11-29 11:47 UTC, Neilsafraoui requested changes
grosse prise de tête la...
pas besoin de callback ici
juste une fonction (basique) qui renvoit le nb le plus grand
function nbLePlusGrand(nb1, nb2) avec un if puis un else

2018-11-29 11:47 UTC, Neilsafraoui commented on javascript/lesson3/exercise3/exercise/index.js
> +var monAppartement = function(boiteauLettres) {
variable dans la fonction ! pas argument dans la déclaration de la fonction

2018-11-29 11:53 UTC, Neilsafraoui requested changes
Problemes de formules, à refaire comme indiqué
(et les document.write sont certes sympa, mais on les utilisera plus tard)

2018-11-29 11:53 UTC, Neilsafraoui commented on javascript/lesson3/exercise5/exercise/index.js
> +    return Math.PI * (p * p)
la, ta formule est : π * P²
or, sur le net je trouve, pour la formule : 2 x π x R (ou 2π * R)

2018-11-29 11:53 UTC, Neilsafraoui commented on javascript/lesson3/exercise5/exercise/index.js
> +    return Math.PI * (p * p)
probleme de formule : diametre (D) = 2 x r (2 fois le rayon, non pas rayon au carré r²)

2018-11-29 11:55 UTC, Neilsafraoui requested changes
j'ai indiqué au tableau que l'exercice 6 doit être fait avec une boucle (tu peux utiliser for)
mais garde ce code en commentaire, il te servira à vérifier si ta fonction avec boucle donne le même résultat que la fonction avec Math.pow

2018-11-29 13:48 UTC, Neilsafraoui approved these changes
Correction indiquée de vive voix (pour éviter de renvoyer encore le fichier)
logique comprise -> je valide

2018-12-10 09:43 UTC, FaXaq commented
Je merge, n'hésite pas à regarder la correction

2018-12-10 09:44 UTC, merged